### ISSUE TITLE
Did this project became closed-source?

### ISSUE THREAD

**Issue by mayoseh** [openpilot-hub/devpilot-intellij#38]
This plugin was recently updated in the marketplace, but there are no changes in the repository. Did this became closed-source? Maybe this should be written in the readme?

**Comment by PerryZhao** [comment]
Thank you for your interest in DevPilot!
Yes, DevPilot has had several updates on the market recently, and you may have noticed that there are also enthusiastic contributors contributing code in the community (allow me to thank @wsliliang  here).

We have **no plans to change the project to closed source** at this time. We are trying to design a more flexible solution than simply putting the prompt words in DevPilot, in order to better adapt to the various LLM and easy referencing of private domain knowledge.
We will show you more about this in our ReadMe in the near future.
Thanks again for your continued interest in DevPilot!
